//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: Generated
//     Created Date: 2026-02-08
//     Description: 
//       Handles the `CountryDeletedEvent` which occurs when a country is deleted.
//       Logs information about the deleted country for auditing and monitoring purposes.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.Countries.EventHandlers;

public class CountryDeletedEventHandler : INotificationHandler<CountryDeletedEvent>
{
    private readonly ILogger<CountryDeletedEventHandler> _logger;

    public CountryDeletedEventHandler(ILogger<CountryDeletedEventHandler> logger)
    {
        _logger = logger;
    }

    public Task Handle(CountryDeletedEvent notification, CancellationToken cancellationToken)
    {
        _logger.LogInformation("Country Deleted: {Name}", notification.Item.Name);
        return Task.CompletedTask;
    }
}
