//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: Generated
//     Created Date: 2026-02-08
//     Description: 
//       Handles the `CountryUpdatedEvent` which occurs when a country is updated.
//       Logs information about the updated country for auditing and monitoring purposes.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.Countries.EventHandlers;

public class CountryUpdatedEventHandler : INotificationHandler<CountryUpdatedEvent>
{
    private readonly ILogger<CountryUpdatedEventHandler> _logger;

    public CountryUpdatedEventHandler(ILogger<CountryUpdatedEventHandler> logger)
    {
        _logger = logger;
    }

    public Task Handle(CountryUpdatedEvent notification, CancellationToken cancellationToken)
    {
        _logger.LogInformation("Country Updated: {Name}", notification.Item.Name);
        return Task.CompletedTask;
    }
}
