//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: Generated
//     Created Date: 2026-02-08
//     Description: 
//       Handles the `CountryCreatedEvent` which occurs when a new country is created.
//       Logs information about the newly created country for auditing and monitoring purposes.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.Countries.EventHandlers;

public class CountryCreatedEventHandler : INotificationHandler<CountryCreatedEvent>
{
    private readonly ILogger<CountryCreatedEventHandler> _logger;

    public CountryCreatedEventHandler(ILogger<CountryCreatedEventHandler> logger)
    {
        _logger = logger;
    }

    public Task Handle(CountryCreatedEvent notification, CancellationToken cancellationToken)
    {
        _logger.LogInformation("Country Created: {Name}", notification.Item.Name);
        return Task.CompletedTask;
    }
}
