//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: Generated
//     Created Date: 2026-02-08
//     Description: 
//       Defines static methods and properties for managing cache keys and expiration 
//       settings for Country-related data. This includes creating unique cache keys for 
//       various country queries (such as getting all countries, countries by ID, etc.), 
//       managing the cache expiration tokens to control cache validity, and providing a 
//       mechanism to refresh cached data in a thread-safe manner.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace CleanArchitecture.Blazor.Application.Features.Countries.Caching;

/// <summary>
/// Static class for managing cache keys and expiration for Country-related data.
/// </summary>
public static class CountryCacheKey
{
    public const string GetAllCacheKey = "all-Countries";
    
    public static string GetPaginationCacheKey(string parameters)
    {
        return $"CountryCacheKey:CountriesWithPaginationQuery,{parameters}";
    }
    
    public static string GetExportCacheKey(string parameters)
    {
        return $"CountryCacheKey:ExportCacheKey,{parameters}";
    }
    
    public static string GetByNameCacheKey(string parameters)
    {
        return $"CountryCacheKey:GetByNameCacheKey,{parameters}";
    }
    
    public static string GetByIdCacheKey(string parameters)
    {
        return $"CountryCacheKey:GetByIdCacheKey,{parameters}";
    }
    
    public static IEnumerable<string>? Tags => new string[] { "country" };
    
    public static void Refresh()
    {
        FusionCacheFactory.RemoveByTags(Tags);
    }
}
