//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: Generated
//     Created Date: 2026-02-08
//     Description: 
//       Defines mapping methods between `Country` entities and related DTOs/commands 
//       within the CleanArchitecture.Blazor application. This mapper facilitates 
//       conversions to support different operations, such as creating, updating, 
//       and projecting country data.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.Countries.Commands.AddEdit;
using CleanArchitecture.Blazor.Application.Features.Countries.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.Countries.Mappers;

#pragma warning disable RMG020
#pragma warning disable RMG012
[Mapper]
public static partial class CountryMapper
{
    public static partial CountryDto ToDto(Country source);
    public static partial Country FromDto(CountryDto dto);
    public static partial Country FromEditCommand(AddEditCountryCommand command);
    public static partial AddEditCountryCommand CloneFromDto(CountryDto dto);
    public static partial void ApplyChangesFrom(AddEditCountryCommand source, Country target);
    public static partial IQueryable<CountryDto> ProjectTo(this IQueryable<Country> q);
}
