//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: Generated
//     Created Date: 2026-02-08
//     Description: 
//       Represents a domain event that occurs when a country is deleted.
//       Used to signal other parts of the system that a country has been removed.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

public class CountryDeletedEvent : DomainEvent
{
    public CountryDeletedEvent(Country item)
    {
        Item = item;
    }

    public Country Item { get; }
}
