//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: Generated
//     Created Date: 2026-02-08
//     Description: 
//       This file defines the command and its handler for deleting one or more
//       Country entities from the CleanArchitecture.Blazor application. It
//       implements caching invalidation logic to ensure that data consistency is
//       maintained. Domain events are triggered for deleted entities to support 
//       integration with other parts of the system.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

using CleanArchitecture.Blazor.Application.Features.Countries.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Countries.Commands.Delete;

public class DeleteCountryCommand : ICacheInvalidatorRequest<Result<int>>
{
    public int[] Id { get; }
    public string CacheKey => CountryCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => CountryCacheKey.Tags;
    
    public DeleteCountryCommand(int[] id)
    {
        Id = id;
    }
}

public class DeleteCountryCommandHandler : IRequestHandler<DeleteCountryCommand, Result<int>>
{
    private readonly IApplicationDbContext _context;
    
    public DeleteCountryCommandHandler(IApplicationDbContext context)
    {
        _context = context;
    }
    
    public async Task<Result<int>> Handle(DeleteCountryCommand request, CancellationToken cancellationToken)
    {
        var items = await _context.Countries
            .Where(x => request.Id.Contains(x.Id))
            .ToListAsync(cancellationToken);
            
        foreach (var item in items)
        {
            // raise a delete domain event
            item.AddDomainEvent(new CountryDeletedEvent(item));
            _context.Countries.Remove(item);
        }
        
        var result = await _context.SaveChangesAsync(cancellationToken);
        return await Result<int>.SuccessAsync(result);
    }
}
