//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: Generated
//     Created Date: 2026-02-08
//     Description: 
//       This file defines the validation rules for the AddEditCountryCommand 
//       used to add or edit Country entities within the CleanArchitecture.Blazor 
//       application. It enforces maximum field lengths and required properties 
//       to maintain data integrity and validation standards.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.Countries.Commands.AddEdit;

public class AddEditCountryCommandValidator : AbstractValidator<AddEditCountryCommand>
{
    private readonly IApplicationDbContext _context;

    public AddEditCountryCommandValidator(IApplicationDbContext context)
    {
        _context = context;

        RuleFor(v => v.Code)
            .MaximumLength(10)
            .NotEmpty()
            .MustAsync(BeUniqueCode)
            .WithMessage("The Code '{PropertyValue}' already exists.");
            
        RuleFor(v => v.Name)
            .MaximumLength(200)
            .NotEmpty()
            .MustAsync(BeUniqueName)
            .WithMessage("The Name '{PropertyValue}' already exists.");
            
        RuleFor(v => v.NameArabic)
            .MaximumLength(200);
            
        RuleFor(v => v.Iso2Code)
            .MaximumLength(2)
            .MustAsync(BeUniqueIso2Code)
            .When(v => !string.IsNullOrWhiteSpace(v.Iso2Code))
            .WithMessage("The ISO2 Code '{PropertyValue}' already exists.");
            
        RuleFor(v => v.Iso3Code)
            .MaximumLength(3)
            .MustAsync(BeUniqueIso3Code)
            .When(v => !string.IsNullOrWhiteSpace(v.Iso3Code))
            .WithMessage("The ISO3 Code '{PropertyValue}' already exists.");
            
        RuleFor(v => v.PhoneCode)
            .MaximumLength(10);
    }

    private async Task<bool> BeUniqueCode(AddEditCountryCommand command, string code, CancellationToken cancellationToken)
    {
        return !await _context.Countries
            .Where(x => x.Id != command.Id)
            .AnyAsync(x => x.Code == code, cancellationToken);
    }

    private async Task<bool> BeUniqueName(AddEditCountryCommand command, string name, CancellationToken cancellationToken)
    {
        return !await _context.Countries
            .Where(x => x.Id != command.Id)
            .AnyAsync(x => x.Name == name, cancellationToken);
    }

    private async Task<bool> BeUniqueIso2Code(AddEditCountryCommand command, string? iso2Code, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(iso2Code)) return true;
        return !await _context.Countries
            .Where(x => x.Id != command.Id)
            .AnyAsync(x => x.Iso2Code == iso2Code, cancellationToken);
    }

    private async Task<bool> BeUniqueIso3Code(AddEditCountryCommand command, string? iso3Code, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(iso3Code)) return true;
        return !await _context.Countries
            .Where(x => x.Id != command.Id)
            .AnyAsync(x => x.Iso3Code == iso3Code, cancellationToken);
    }
}
