//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: Generated
//     Created Date: 2026-02-08
//     Description: 
//       This file defines the command for adding or editing a country entity,
//       including validation and mapping operations. It handles domain events
//       and cache invalidation for updated or newly created country.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

using CleanArchitecture.Blazor.Application.Features.Countries.Caching;
using CleanArchitecture.Blazor.Application.Features.Countries.Mappers;

namespace CleanArchitecture.Blazor.Application.Features.Countries.Commands.AddEdit;

public class AddEditCountryCommand : ICacheInvalidatorRequest<Result<int>>
{
    [Description("Id")]
    public int Id { get; set; }
    
    [Description("Code")]
    public string Code { get; set; } = string.Empty;
    
    [Description("Name")]
    public string Name { get; set; } = string.Empty;
    
    [Description("Name (Arabic)")]
    public string? NameArabic { get; set; }
    
    [Description("ISO2 Code")]
    public string? Iso2Code { get; set; }
    
    [Description("ISO3 Code")]
    public string? Iso3Code { get; set; }
    
    [Description("Phone Code")]
    public string? PhoneCode { get; set; }
    
    [Description("Is Active")]
    public bool IsActive { get; set; } = true;

    public string CacheKey => CountryCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => CountryCacheKey.Tags;
}

public class AddEditCountryCommandHandler : IRequestHandler<AddEditCountryCommand, Result<int>>
{
    private readonly IApplicationDbContext _context;
    
    public AddEditCountryCommandHandler(IApplicationDbContext context)
    {
        _context = context;
    }
    
    public async Task<Result<int>> Handle(AddEditCountryCommand request, CancellationToken cancellationToken)
    {
        if (request.Id > 0)
        {
            var item = await _context.Countries.FindAsync(new object[] { request.Id }, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"Country with id: [{request.Id}] not found.");
            }
            
            CountryMapper.ApplyChangesFrom(request, item);
            // raise an update domain event
            item.AddDomainEvent(new CountryUpdatedEvent(item));
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            var item = CountryMapper.FromEditCommand(request);
            // raise a create domain event
            item.AddDomainEvent(new CountryCreatedEvent(item));
            _context.Countries.Add(item);
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
    }
}
